# Generated by Django 5.2.2 on 2025-08-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('case_number', models.DecimalField(decimal_places=0, max_digits=20)),
                ('date', models.DateField()),
                ('case_status', models.CharField(max_length=100)),
                ('court_name', models.CharField(max_length=100)),
                ('judges', models.CharField(max_length=100)),
                ('hearing_dates', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
